

site_name: ADLStream2
site_url: https://adlstream.readthedocs.io
site_description: Asynchronous dual-pipeline deep learning framework for online data stream mining.
site_author: Pedro Lara-Benítez & Manuel Carranza-García

repo_url: https://github.com/pedrolarben/ADLStream/
edit_uri: ""

theme:
  name: material
  custom_dir: 'docs/theme'
  favicon: images/favicon.ico
  logo: images/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
      primary: 'teal'
      accent: 'deep orange'
    - scheme: slate 
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: 'blue grey'
      accent: 'deep orange'
  font:
    text: Roboto
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.tabs

nav:
  - Home: index.md
  - Getting started: 
    - Installation: install.md
    - First example: getting_started.md
  - API: 
    - API/index.md
    - ADLStream: API/ADLStream2.ADLStream2.md
    - Data:
      - Stream: 
        - BaseStream: API/data/stream/BaseStream.md
        - DataStream: API/data/stream/DataStream.md
        - FileStream: API/data/stream/FileStream.md
        - CSVFileStream: API/data/stream/CSVFileStream.md
        - KafkaStream: API/data/stream/KafkaStream.md
        - RiverStream: API/data/stream/RiverStream.md
        - FakeStream: API/data/stream/FakeStream.md
      - Preprocessing: 
        - BasePreprocessor: API/data/preprocessing/BasePreprocessor.md
        - MinMaxScaler: API/data/preprocessing/MinMaxScaler.md
        - MeanNormalizationScaler: API/data/preprocessing/MeanNormalizationScaler.md
        - StandardizationScaler: API/data/preprocessing/StandardizationScaler.md
      - BaseStreamGenerator: API/data/BaseStreamGenerator.md
      - ClassificationStreamGenerator: API/data/ClassificationStreamGenerator.md
      - MovingWindowStreamGenerator: API/data/MovingWindowStreamGenerator.md
    - Evaluation:
      - BaseEvaluator: API/evaluation/BaseEvaluator.md
      - InterleavedChunkEvaluator: API/evaluation/InterleavedChunkEvaluator.md
      - PrequentialEvaluator: API/evaluation/PrequentialEvaluator.md
      - metrics: API/evaluation/metrics.md
    - Models: 
      - create_model: API/models/models.md
      - MLP: API/models/mlp.md
      - LSTM: API/models/lstm.md
      - GRU: API/models/gru.md
      - ERNN: API/models/ernn.md
      - ESN: API/models/esn.md
      - CNN: API/models/cnn.md
      - TCN: API/models/tcn.md
      - Transformer: API/models/transformer.md
  - About:
    - Research: research.md 
    - Authors: authors.md
    - Contributing: contributing.md
    - License: license_page.md

extra:
  generator: false 
  version:
    provider: readthedocs     

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            inherited_members: True
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
          rendering:
            show_source: true
            heading_level: 3

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
